### ISSUE TITLE
Add Editor Docs & Presets

### ISSUE THREAD

**Issue by atakantepe** [primefaces/primevue-tailwind#140]

**Comment by atakantepe** [comment]
This component will not be added to primevue-tailwind. Due to being third-party, it has limitations for PassThrough. 

We will have our editor in the premium components suite by Prime. This will allow us to add Passtrough from the start.

**Comment by IsAvaible** [comment]
Since my project needed an editor component, I customized the Editor styling by combining [Quill v2.0.2 styles](https://github.com/primefaces/primereact/blob/a5d0c1cb16960b9d5215c52fe8e457f9941e0812/components/lib/editor/EditorBase.js) with [PrimeVue’s editor styles](https://github.com/primefaces/primevue/blob/938beb2c62f184ce4871fbdef966829ad03bf393/packages/primevue/src/editor/style/EditorStyle.js#L844), adjusted to work with Tailwind CSS classes.

To implement this setup in your own project, follow these steps:
- Download [this file](https://gist.github.com/IsAvaible/88d5c32a23d88d400a4a9c023d104d48) and put it into `src/assets/primevue` (or wherever you store all your PrimeVue Tailwind styles.
- In `tailwind.css` import the file using 
  ```
  /* Editor */
  @import './editor';
  ```

Note that until [this issue](https://github.com/primefaces/primevue/issues/5606) is not fixed, you need to use [this workaround](https://github.com/primefaces/primevue/issues/5606#issuecomment-2206793034) to make PrimeVue work with Quill 2.0.
