### ISSUE TITLE
Copy & Paste does not work

### ISSUE THREAD

**Issue by chiarotto** [primefaces/primevue-tailwind#166]
Firstly, I want to congratulate you on your wonderful project. Perhaps implementing the ability to copy and paste the text present in a button or chip could add more value to the project. Currently, the text displayed by a button cannot be copied. I'm developing an enterprise application used by four EU countries, and the ability to copy and paste text speeds up the work of the user.

I'm using firefox and there is no change to copy a test of the following button:

` <Button label="Hello world"   link />`

Now I'm thinking of using another component or raw <a> to be used as a link and give the user the possibility to copy and paste the text 'Hello World'.

**Comment by atakantepe** [comment]
Hi, this is the expected behavior from the Primevue Button. The tailwind version actually mirrors the styled version. But if you want to be able to copy the text inside the button, you can easily make it. 
The presets are not like rules; they are just helpers for starting to build your own presets/design systems. 

So for buttons, you just need to remove "select-none" from the root. That's easy 👍
![image](https://github.com/primefaces/primevue-tailwind/assets/28745098/f3840fa7-7cff-4bd3-a280-b4576c47911d)
