### ISSUE TITLE
Can dark mode be deactivated for all components?

### ISSUE THREAD

**Issue by Mistyrios** [primefaces/primevue-tailwind#176]
Hello,

I'd like to know if it's possible to disable dark mode for all components on a site where you don't want to have dark mode, because I have a problem when someone has activated dark mode on their computer.

**Comment by WatCodeDatCode** [comment]
This setting is controlled by tailwind, which uses `prefers-color-scheme` media feature by default and which has already been considered in the PrimeVue presets. 

The quickest way to deactivate dark mode is by setting the "darkMode" value in your tailwind config to make use of manual toggling. Since it's unlikely you would have a generic "dark" class somewhere in a parent container, this should solve it: https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually

**Comment by atakantepe** [comment]
Hi, In primevue-tailwind's tailwind config, we use the `dark mode: 'class. This way, the dark mode is not linked to your preferred color scheme. You can also check @WatCodeDatCode's suggested link from tailwindcss.

I will be closing this issue, but you can always re-open it.
