### ISSUE TITLE
Menubar subMenu overflow browser window

### ISSUE THREAD

**Issue by sojoio** [primefaces/primevue-tailwind#212]
If menubar is aligned right submenu dropdowns overflow container instead of being forced left. 

![image](https://github.com/primefaces/primevue-tailwind/assets/144434450/b38945ea-d3d1-468c-a4c4-352b26dea160)

**Comment by atakantepe** [comment]
Hi, this issue is related to PrimeVue Core. As you noticed, there is no calculation for it. I directed this to the primevue team. When they add a solution, it will also be implemented in this project.

For now, I can suggest customizing the preset for this need by changing left-full to right-full in the menubar preset.

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
