### ISSUE TITLE
Vertical divider has 2px width instead of 1px

### ISSUE THREAD

**Issue by vitalysoftech** [primefaces/primevue-tailwind#267]
This can be noticed in documentation:

https://tailwind.primevue.org/divider/#vertical

Compare this with non-Tailwind version:

https://primevue.org/divider/#vertical

Tailwind version of Divider is 2px, whereas it must be 1px.

**Comment by atakantepe** [comment]
Hi, this issue has likely been resolved in the latest updates.
If you're still experiencing the problem, please feel free to reopen the issue or create a new one with more details.

**Comment by lmc3s3f0r** [comment]
Hi @atakantepe . According to your comment on September 23rd, this should have been fixed in primevue@4.1.1 (released on October 17th) but I'm on that version and the Divider width is still 2px.

Not sure if it was reviewed and fixed later as I can't currently update Primevue on my project (we faced some breaking changes when updating Vue version, and we rolled back), but I wanted to ask just in case. 

My poor UI designer is having some OCD issues with this XD

**Comment by lmc3s3f0r** [comment]
Found a way to fix it if you're using a theme.

Go to divider/index.js and find this line:
`'before:absolute before:left-1/2 before:top-0 before:transform before:-translate-x-1/2': props.layout == 'vertical'`

Change it to:
`'before:absolute before:top-0 before:left-[calc(50%-0.5px)]': props.layout == 'vertical'`

This shows a perfect 1px vertical line.
