### ISSUE TITLE
Bottom border for focus frame in DataTable component is not drawn

### ISSUE THREAD

**Issue by vitalysoftech** [primefaces/primevue-tailwind#268]
It can be reproduced from documentations:

https://tailwind.primevue.org/datatable/#row_selection

![image](https://github.com/primefaces/primevue-tailwind/assets/36422002/b753a712-4802-446d-ba53-8a7728ce5108)

**Comment by Zercerium** [comment]
funfact: the problem is the drawn border which covers the box-shadow (ring).
if you remove the border-bottom-witdh in the td elements you can see the full ring.

This behaviour is in both themes present but in Lara is it not that visible because the box shadow is 2px bright and only one pixel is covered by the border. In Aura one of one pixel is covered and so no border visible :(

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
