### ISSUE TITLE
Enhanced Integration of Dynamic Styles in PrimeVue and TailwindCSS

### ISSUE THREAD

**Issue by hibrandonevans** [primefaces/primevue-tailwind#40]
Hello PrimeVue team,

I'm currently using PrimeVue with TailwindCSS and have noticed an interesting behavior. The library offers a convenient global setting in presets, but when dynamically loaded components, such as RadioButton, are used, they inject a style tag with data-primevue-style-id="base" into the document. This results in separate base styles.

![image](https://github.com/primefaces/primevue-tailwind/assets/112993120/cd4c8a6d-44f6-44b7-b93d-9375228bc4f4)

I was wondering if it would be possible to either merge these dynamically generated base styles into the global presets or, preferably, append the base classes directly to the corresponding components themselves (e.g., RadioButton). This approach could simplify styling consistency and enhance compatibility, especially for scenarios like using these components within Web Components.

I would appreciate your thoughts on this possibility.

**Comment by mertsincan** [comment]
Hello,

Thanks a lot for your feedback! But, the "base" style is a separate CSS used in both unstyled and styled modes. That's why we don't consider combining it with other css. If you have any problems with these styles and append them, please don't hesitate to raise an issue in PrimeVue Github.

Best Regards,
