### ISSUE TITLE
The picklist component does not rotate its move to target  buttons at the right breakpoint

### ISSUE THREAD

**Issue by gertst** [primefaces/primevue-tailwind#87]
See example at https://tailwind.primevue.org/picklist/#basic: 
When making your browser smaller/wider, the breakpoint to rotate the arrows 90° is not the same breakpoint as when the left and right panel go below each other.

Where can I (temporary) fix this myself?

Thanks!

**Comment by mertsincan** [comment]
Good catch! It does not make sense to use the breakpoint props of our components in Tailwind or any other preset structure. There are special classes in CSS frameworks for such operations.(md:*, xl:*, and custom breakpoint prefixes) Using them is the way we recommend. That's why we will update the source code of our demo as soon as possible. Thanks for your notice!
